name: Docker Image CI

on:
  workflow_dispatch:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)      

    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
   
    - name: build & push the image
      run: |
          docker buildx build --push \
            --tag georgedimac/alpine-with_ssh_client:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
